### ISSUE TITLE
Using libflac on armv7l - ASR service does not detect text

### ISSUE THREAD

**Issue by jhoelzl** [Uberi/speech_recognition#125]
Hello,

i want to use this module on armv7l (`platform.machine()` returns this name).

In function `get_flac_converter` (https://github.com/Uberi/speech_recognition/blob/master/speech_recognition/__init__.py#L920-L942) i adjusted the path of the FLAC encoder to a preinstalled one because `armv7l` is not in the list `compatible_machine_types`:

`flac_converter = "/usr/lib/gstreamer-1.0/libgstflac.so"`

Now ASR runs without errors, however, no text is detected by the ASR services from microphone stream. I also tested wav audio files but also no detection occurred.

This only happens when using Google as ASR service. Bing and Wit.ai work because the library does not use flac encoded audio data but wav.

Does anybody have an idea how to overcome this issue?
Thanks!

**Comment by Uberi** [comment]
Hi @jhoelzl,

The flac converter needs to be an executable, not a shared library. You'll want to install the converter utility, which should usually be published by your distro. If you're on x86, we bundle a statically linked one already, which means no changes are needed. Otherwise, you can build it from source using the step by step instructions in our documentation.

Also, I recommend putting that flac converter on your PATH variable, so the library can find it automatically. That means you won't have to modify the library code.

**Comment by jhoelzl** [comment]
Hello @Uberi,

thanks for support! I tried your instruction about FLAC, however, in our system we do not have a package manager (like `apt-get`).

When i download http://www.linuxfromscratch.org/blfs/view/7.8/multimedia/flac.html and run `./configure` i get:

> configure: error: no acceptable C compiler found in $PATH

so i guess we have do compile this library on our own.

**Comment by jhoelzl** [comment]
Okay, we could successfully compile it :)
