### ISSUE TITLE
Support Google Cloud Speech API

### ISSUE THREAD

**Issue by edevil** [Uberi/speech_recognition#128]
It seems the speech API from Google is changing to https://cloud.google.com/speech/. We cannot obtain API keys to the old speech API.

**Comment by Uberi** [comment]
Hi @edevil,

The Cloud Speech API looks pretty interesting! I've applied but currently do not have access to it - support will be added when we do. This issue will be updated with progress for that.

**Comment by jhoelzl** [comment]
Hi @Uberi, today Google announced open Beta of Speech API: https://cloud.google.com/speech/?authuser=1.

I tried `recognize_google` with my own API-Key, but it did not work. I suppose we have to change the API Call for the new version.

**Comment by bodiroga** [comment]
Hi @Uberi!

Here you have the python samples that Google has provided: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/speech/api

Many thanks for all the work you are doing, awesome library!

**Comment by Uberi** [comment]
Thanks for the links @jhoelzl and @bodiroga - keep an eye on this issue for progress updates!

**Comment by hoangpx** [comment]
Which api are you using ? The only google speech api available I can found is https://cloud.google.com/speech/ 
If I want to implement my own api, can I do it ? Could you give me some thought ?

**Comment by mdhaber** [comment]
Hi @Uberi, just wanted to +1 this. Thanks so much for this great library; looking forward to using it with my own key!

**Comment by thingdeux** [comment]
Good luck! 

Great library - +1

**Comment by AliceGab** [comment]
Hello everyone, 

I have few questions about the Cloud speech API from Google. 

1)  I have the same problem as @jhoelzl : r.recognize_google(audio) works but r.recognize_google(audio, key="myOwnKey") doesn't. I am confused why. Is there another way to access the API with Python ? 

2) I have a 15 sec limitation, is that normal ? 

Thanks a lot for your help :) 
Alice

**Comment by Thynix** [comment]
I've started poking at the beta; it's interesting. My impression is this is a distinct service, so the question is whether to considering the existing one superseded by this one (probably not appropriate at least until this is labeled stable; that the example code from a few months ago speaks volumes) or introduce a `recognize_google_cloud()`.

There are [REST](https://cloud.google.com/speech/reference/rest/) and [gRPC](https://cloud.google.com/speech/reference/rpc/) variants. There's an [API explorer](https://developers.google.com/apis-explorer/?hl=en_US#p/speech/v1beta1/) which allows interactively building and trying requests which is great. (It doesn't use your account though, which can make for odd artifacts when jobs aren't accessible with one's own API keys.)

However, there are some limitations that I've been running up against when trying to run speech-to-text on half-hour scale things: there keep being time limits. (Which seems reasonable - from looking at the behavior when using the API explorer it appears to recognize in real-time instead of faster.) Things beyond a minute (IIRC) as of this writing require service-level authentication which looks complex. Google both [recommends using it](https://cloud.google.com/speech/docs/common/auth) and [recommends using](https://developers.google.com/identity/protocols/application-default-credentials) [their API client library](https://developers.google.com/api-client-library/python/) in order to use it. So this presents another choice: accept that use of the API is length-limited, introduce an optional dependency on Google's API client library, or bother to figure out how to implement just the desired auth parts.
