### ISSUE TITLE
How to recognise a *.amr file? 

### ISSUE THREAD

**Issue by chenjianjx** [Uberi/speech_recognition#135]
I tried to transcribe an *.amr file, and I got "file does not start with RIFF id" error and "file does not start with FORM id" error. 

Here is my code: 

````
def english_speech_parse(media_file_path):
    r = sr.Recognizer()
    with sr.AudioFile(media_file_path) as source:  #exception here
        audio = r.record(source)  
````

**Comment by chenjianjx** [comment]
I did a debug on aifc.py and it showed chunkname of my audio file is    b'#!AM'

**Comment by Uberi** [comment]
Hi @chenjianjx,

This library only supports the WAV, FLAC, and AIFF/AIFC audio formats when reading audio from files. AMR is not supported due to requiring really heavy dependencies.

I recommend converting your AMR files into AIFF, and then loading them into your program. One way you can do this is with FFmpeg:

```sh
ffmpeg -i input.amr output.aiff
```

If you want to avoid creating new files on disk, it's also possible to do the FFmpeg conversion in memory, and then make an AudioFile object out of the result. Let me know if you'd like an example.

**Comment by chenjianjx** [comment]
Thanks.
