### ISSUE TITLE
Getting time offsets of beginning and end of each word

### ISSUE THREAD

**Issue by burakicel** [Uberi/speech_recognition#142]
Is it possible to get time offsets of beginning and end of each word using this library ? Preferably with sphinx ?

**Comment by Uberi** [comment]
Hi @burakicel,

We don't support this directly since it's a rather niche use case. However, you can do this using the library by using `show_all=True` for `recognize_sphinx`.

When the `show_all` parameter is `True`, the function returns a decoder object. You can get the timestamps out of the decoder object using something like the code in [this StackOverflow answer](https://stackoverflow.com/questions/37973541/segment-timestamps-in-pocketsphinx).

Please feel free to re-open if you have any further questions.
