### ISSUE TITLE
Attribute Microphone

### ISSUE THREAD

**Issue by Soser** [Uberi/speech_recognition#21]
Hi, I am new in this topic.
So, I have installed the SpeechRecognition without problem, but when I tried to test the example I got the message "AttributeError:'module' object has no attribute 'Microphone'".
I am using Python 3.4 and SpeechRecognition was installed using the files of this page. Besides I have updated using PIP but I still get the same message.
I don't know if SpeechRecognition only  works in a specific version of Python or if it is neccessary to use other libraries or an extra microphone because I am using the internal microphone of my laptop.
Thanks

**Comment by Uberi** [comment]
Please read the [README](https://github.com/Uberi/speech_recognition#the-srmicrophone-class-is-missingnot-defined).

In short, you need to install PyAudio in order to use the `Microphone` class. Installers for Windows are provided in the download. On Linuxes, you can likely obtain PyAudio via your package manager.
