### ISSUE TITLE
Change event for end of phrase

### ISSUE THREAD

**Issue by gssci** [Uberi/speech_recognition#226]
I'm trying to use the API in an application where I listen to the microphone as long as a key is pressed and as soon as the key is release, send that audio for recognition.
This seems like a natural extension to the API, but I see that the .listen(-) function waits until there's silence to start the recognition.

Do you have any suggestions on how to correctly implement this using the api?

**Comment by jhoelzl** [comment]
Hi @gssci,

i implemented almost the same application as you described. In the end i used Pyhon package `termios` for detecting the keyboard "Push2Talk" functionality, because this is very hard to implement with standard python. It works, but i hate the additional window that appears. How did you detect the key release?

During the keyboard press i listened to the microphone input using the loop from PyAudio (https://people.csail.mit.edu/hubert/pyaudio/ > Documentation & Examples > Record) and then only passed the resulting wav data into the SpeechRecognition library. I also added 0.5 seconds to the recording before and after the keyboard press to avoid cutting speech segments.

However, it would be awesome if such a feature would be integrated in this library.

**Comment by gssci** [comment]
Hey @jhoelzl! Thanks for the tip, I will let you know how it works out, I can't use termios since I am working on a Windows machine, but within the GUI (Tkinter) I can detect keypress and keyrelease events

**Comment by jhoelzl** [comment]
Hi @gssci, actually i am also using Tkinter for the keypress and key release events.

**Comment by gssci** [comment]
It worked out just fine, I had to create a button on the interface for the press and release events, since each os has an automatic key repetition feature, so during keypress multiple events were detected. I simply coordinated the events using a boolean flag, on keypress I set pressed = true, and while pressed i record a message on a separate thread, on the release event I set the pressed = false, the loop stops and I queue the recorded message for transcription using the SR library. :)

**Comment by Uberi** [comment]
Missed this issue before, but good to hear you got it to work! I'll close this for now.
