### ISSUE TITLE
Implements AudioSource

### ISSUE THREAD

**Issue by AlEmerich** [Uberi/speech_recognition#243]
Hi Uberi ! 

I have been in trouble since a few day to implements AudioSource class for writing my own audiosource read by the recognizer. 
I need to do that to be able to read from a microphone without PyAudio.

 The steps to reproduce is basically simple:

```
class myNewClass(Audiosource):
    __init__(self):
        pass

    __enter__(self):
        pass

    __exit__(self, ...):
        pass

r = sr.Recognizer()
s = myNewClass()
with s as source:
	print("Say something!")
	audio = r.listen(source)

try:
	print("You said: " + r.recognize_google(audio,language='FR'))
	return r.recognize_google(audio,language='FR')
except sr.UnknownValueError:
	print("Google Speech Recognition could not understand audio")
	return ''
except sr.RequestError as e:
	print("Could not request results from Google Speech Recognition service; {0}".format(e))
	return ''
```

I, of course, have all the data the recognizer need to work with (like stream or variables).
But when I run the code, the recognizer kicked me out saying that my class is not and audio source, line 530.

Am I doing something wrong?

Thanks by the way for your work, it really make things simplier !

# Edit

I found a workaround, which is using s directly in listen and not source...

**Comment by Uberi** [comment]
Hi @AlEmerich,

The code you posted doesn't work - it has a bunch of syntax errors and is missing implementations for `__enter__` and `__exit__`. You are likely getting that error because `s.__enter__` must return an `AudioSource`-derived object.

For example, check out how the [Microphone class](https://github.com/Uberi/speech_recognition/blob/master/speech_recognition/__init__.py#L132) does it.

**Comment by AlEmerich** [comment]
Thanks for your help, I did detect that mistake for the __enter__ function. The syntax error surely comes from indentation format when I typed the message, sorry for that.

Just to be sure, when __enter__ and __exit__ is triggered ? At the beginning and the end of the listen function or at the destruction of the AudioSource object ? My problem now is that listen read nothing but it comes from the code I use to get stream, so not related with SpeechRecognition.

The main reason I opened the issue is now resolved for me, you can mark it as such.
Thanks for your feedback !

**Comment by Uberi** [comment]
Great to hear @AlEmerich! As for the `listen` reading nothing, I recommend checking out this troubleshooting entry: https://github.com/Uberi/speech_recognition/#the-recognizer-hangs-on-recognizer_instancelisten-specifically-when-its-calling-microphonemicrophonestreamread

The `__enter__` function is triggered exactly when you enter the `with` block. Likewise, the `__exit__` function is triggered exactly when you leave the `with` block (including if you leave it due to an exception being raised).
