### ISSUE TITLE
Time limit using Google Speech Recognition API engine?

### ISSUE THREAD

**Issue by pnmartinez** [Uberi/speech_recognition#247]
Hi everyone,

When I try to recognize speech from a long audio, say t >30 s, the engine won't return anything. 

I know that Google Speech Recognition API is an **outdated service**, so I'm having difficulties **finding detailed documentation** on it. If that's not possible, I'd specifically need _the limits_ of the API:

- Maximum audio duration possible.
- Pricing: is there any usage limit? Is Google Cloud Speech API pricing still aplicable? 
- License.

Disclaimer: sorry about my a-little-bit-weak english

**Comment by Uberi** [comment]
Hi @pnmartinez,

Note that the Google Speech API and the Google Cloud Speech API are two very different things. Both APIs support a maximum of around 1 minute of audio per request in the configuration we're using them in. While the former is free, the latter costs $0.006 USD per minute after the first hour, which is free.

Not sure what you mean by license - do you mean SLAs for these APIs?

For longer audio streams, I recommend using the IBM Watson APIs, available via `recognizer_instance.recognize_ibm`.

**Comment by pnmartinez** [comment]
Hi @Uberi,

First of all, thanks for answering! That's exactly the problem: I keep finding info about the Cloud Speech API, obscuring results speaking about the Speech API. Can you handle me any link to check for myself that pricing?  

Also, is there any possibility to extend that maximum duration?

Last but not least, I do refer the SLAs. 

I'd like to stick to Google or Wit, but I'll check IBM's API!






Do you have any link in which I could check the

**Comment by Uberi** [comment]
Hi @pnmartinez,

Check out the [pricing page](https://cloud.google.com/speech/pricing) for costs. For long-form audio using Google Cloud Speech, you'd need to use the async recognize endpoint - check out the [audio limits](https://cloud.google.com/speech/limits) page for details. You'd need to implement that using the official clients, since the process is quite a bit more involved.

As for SLAs, as far as I can tell Google [doesn't offer one](https://cloud.google.com/terms/sla/) for any of their speech-related products, and neither does Wit.ai. IBM does seem to offer a basic one, which you can see in the terms when you sign up.

**Comment by pnmartinez** [comment]
@Uberi 

I guess the precise info I was looking for is simply not out there to get... Anyway, thanks man, appreciate it. You've done an impressive work with this library, and it's awesome that you still take some time to answer this not-so-code-related issues :)

So I'm closing.

Keep it up!
