### ISSUE TITLE
Issues with Pulse Audio (Microfones)

### ISSUE THREAD

**Issue by ryanvade** [Uberi/speech_recognition#27]
I am on Arch Linux with python 3.4 and pyaudio 0.2.8-1 and have this issue:
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed

Is is possible to specify Pulse audio instead of Alsa?

**Comment by Uberi** [comment]
Hi ryanvade,

This seems to be a PyAudio issue. That said, PyAudio uses JACK, and it seems like it's not configured correctly for your situation. Try checking your settings in the JACK audio control panel and make sure that your audio devices are detected correctly.

**Comment by lefos99** [comment]
I am using Ubuntu 12.04 and i have this problem when i am running speech recognition with microphone:
<code>ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib audio/pcm_bluetooth.c:1614:(audioservice_expect) BT_GET_CAPABILITIES failed : Input/output error(5)
ALSA lib audio/pcm_bluetooth.c:1614:(audioservice_expect) BT_GET_CAPABILITIES failed : Input/output error(5)
ALSA lib audio/pcm_bluetooth.c:1614:(audioservice_expect) BT_GET_CAPABILITIES failed : Input/output error(5)
ALSA lib audio/pcm_bluetooth.c:1614:(audioservice_expect) BT_GET_CAPABILITIES failed : Input/output error(5)
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server socket
jack server is not running or cannot be started</code>


any ideas?

**Comment by Uberi** [comment]
Hmm, not sure exactly what the issue is here, but these might help:

* If you're using 32-bit Python on a 64-bit machine, make sure to install the 32-bit version of JACK as well as the 64-bit version. Same goes for PyAudio.
* Some of the suggestions mentioned [here](http://askubuntu.com/questions/224151/jack-server-could-not-be-started-when-using-qjackctl) and [here](https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit).
* Make sure your audio devices are correctly set up - open `qjackctl` and make sure all of your microphones and speakers are correctly detected.

**Comment by silvahwuff** [comment]
@lefos99 I was able to get around the "jack server is not running or cannot be started" by issuing `pulseaudio --kill`, then starting `qjackctl` and hitting the Start button. Unfortunately, I am now getting this output...

    ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
    ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
    ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
    ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
    ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
    bt_audio_service_open: connect() failed: Connection refused (111)
    bt_audio_service_open: connect() failed: Connection refused (111)
    bt_audio_service_open: connect() failed: Connection refused (111)
    bt_audio_service_open: connect() failed: Connection refused (111)
    ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave

As I understand it, the `bt_audio_service_open: connect() failed: Connection refused (111)` lines can be ignored as a "Bluetooth libraries installed but no Bluetooth device plugged in" warning that isn't affecting anything. As for the rest, I'm not sure what the problem is or how to go about fixing it.

**Comment by Uberi** [comment]
More Linux troubleshooting info has been added to the README [over here](https://github.com/Uberi/speech_recognition#user-content-on-ubuntudebian-i-get-errors-like-jack-server-is-not-running-or-cannot-be-started-or-cannot-lock-down--byte-memory-area-cannot-allocate-memory).

Please re-open if issues persist.
