### ISSUE TITLE
Python3 PocketSphinx Setup

### ISSUE THREAD

**Issue by jehoshua7** [Uberi/speech_recognition#297]
Steps to reproduce
------------------

Run Transcribe example
https://github.com/Uberi/speech_recognition/blob/master/examples/audio_transcribe.py

Expected behaviour
------------------

Process english.wav and produce output transcription

Actual behaviour
----------------

Getting error
Sphinx error; missing PocketSphinx module: ensure that PocketSphinx is set up correctly.

```
Google Speech Recognition could not understand audio
Traceback (most recent call last):
  File "audio_transcribe.py", line 38, in <module>
    print("Google Cloud Speech thinks you said " + r.recognize_google_cloud(audio, credentials_json=GOOGLE_CLOUD_SPEECH_CREDENTIALS))
  File "/home/********/.local/lib/python2.7/site-packages/speech_recognition/__init__.py", line 808, in recognize_google_cloud
    except: raise AssertionError("``credentials_json`` must be ``None`` or a valid JSON string")
AssertionError: ``credentials_json`` must be ``None`` or a valid JSON string
```

System information
------------------

My **system** is Kubuntu 16.04.3 LTS, kernel 4.4.0-101-generic

My **Python version** is 2.7.12 and 3.5.2 (both installed)

My **Pip version** is 9.0.1 from /home/********/.local/lib/python2.7/site-packages (python 2.7)

My **SpeechRecognition library version** is 3.7.1

My **PyAudio library version** is 0.2.11

I **installed PocketSphinx from** https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst  (python 3 and pip3)

**Comment by Uberi** [comment]
Hi @jehoshua7,

You'll want to install PocketSphinx if you're using `recognize_sphinx` - I've written a guide for how to do so [here](https://github.com/Uberi/speech_recognition/blob/master/reference/pocketsphinx.rst).

Additionally, in the code you'll want to replace `INSERT THE CONTENTS OF THE GOOGLE CLOUD SPEECH JSON CREDENTIALS FILE HERE` with the actual Google Cloud Speech JSON credentials. Otherwise, the web APIs won't work properly.
