### ISSUE TITLE
 sudo python microphone_recognition.py  stuck not producing results. 

### ISSUE THREAD

**Issue by FahadMaqbool** [Uberi/speech_recognition#353]
Hello, I tried to use this fantastic piece of code yesterday, from quick start I started to installed it and then tried it using

 pip install SpeechRecognition.

To quickly try it out, run python -m speech_recognition

it worked fine with live speech recognition. but there is problem when I try to run sudo python microphone_recognition.py in examples directory as I wanted to test all other recognizers. 
sudo python calibrate_energy_threshold.py  codes runs fine as well. but i dont know how to run microphone_recognition.py as it stucks on say something as shown below. 
Do I need to do add credentials for all the recognizers first, or should it atleast give me some output without giving any credentials. kindly guide me.

fahad@fahad-Latitude-E6400:~/Downloads/speech_recognition-master/examples$ sudo python calibrate_energy_threshold.py 
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Say something!
Google Speech Recognition thinks you said can you listen me
fahad@fahad-Latitude-E6400:~/Downloads/speech_recognition-master/examples$ sudo python microphone_recognition.py
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Say something!

**Comment by palikar** [comment]
Hi @FahadMaqbool ,

you do in fact have to provide credentials for the majority of the APIs so that the example in `microphone_recognition.py` can work. The code of the example is fairly well comented and can be found [here](https://github.com/Uberi/speech_recognition/blob/master/examples/microphone_recognition.py). 

If you are stuck on "Say something!", you should checkout your microphone settings and/or the energy threshold of the `Recognizer` object. From what I see, everything works properly but the microphone input isn't being picked up because maybe it's not "loud" enough..

You can also look up the [documentation](https://github.com/Uberi/speech_recognition/blob/master/reference/library-reference.rst) on how to use the library in your code.

Feel free to reopen the issue if there are problems with the library.
