### ISSUE TITLE
possible to do recognize_google() using .flac files directly?

### ISSUE THREAD

**Issue by jeremygray** [Uberi/speech_recognition#56]
Very nice project! Thanks for your work on this.

Perhaps there's an easy way to do the following, sorry if I missed it. In my application (I contribute to PsychoPy), I have speech snippets saved on disk, and they are often already in .flac format to save disk space. Is there a way to pass those files directly to google using SR, or does the SR API structure mean that my application has to convert them to .wav, pass the new file name to SR, and SR then converts from .wav back to .flac for sending to google?

**Comment by Uberi** [comment]
Hi @jeremygray,

At the moment, you'll need to convert the audio to WAV manually, then pass them to the library. Support for automatic FLAC to PCM WAV conversion is difficult due to the `flac` utility only supporting extensible WAV.

Ensure that your converted output is PCM WAV rather than, say extensible or compressed WAV!

**Comment by Uberi** [comment]
By the way, you can do this by running:

    sox SOME_FLAC_FILE.flac SOME_WAV_FILE.wav

**Comment by jeremygray** [comment]
I'm thinking about completely avoiding the need to go through WAV at all (if its already in flac format). Currently the `AudioData.get_flac_data()` method assumes that the data (`self.frame_data`) are always WAV, converts to flac using subprocess calls, and then loads the newly-flac'ed frame-data into memory. What if there were just a format flag (e.g., set during init) so that the method could then do this as the first line of the method, e.g.,

    if self.frame_data_format == 'flac':
        return self.frame_data

If you are open to this, I'll see if I can actually make it work, and submit a pull request.

**Comment by Uberi** [comment]
Unfortunately, that would break `recognize_wit` and `recognize_att`, since they use PCM WAV as their upload format.

Perhaps a `WavFile.from_flac(filename_or_fileobject)`function would be better: a static method of WavFile that returns a WavFile instance constructed from the PCM data extracted from the FLAC file.

I don't have time at the moment, but contributions here would be highly welcome!

**Comment by Uberi** [comment]
The new `AudioFile` class in version 3.4.1 now implements FLAC and AIFF loading, so this use case should be covered.
