### ISSUE TITLE
Not work when speech sample is too long

### ISSUE THREAD

**Issue by tuming1990** [Uberi/speech_recognition#61]
Hi,

I'm trying to use it to recognize some long speech samples.

The first one is about 45s. But it only returns the first few words no matter how large the pause_threshold is. The second one is over 1min and it can't be recognized, only returning exception information "request failed, ensure that key is correct and quota is not maxed out".

Is there a solution for this? or the only way is to segment my speech samples? 

Thank you very much!

**Comment by Uberi** [comment]
Unfortunately, this is a known issue with the Google Speech API. To get around this length limit, you can try another API backend like Wit.ai - see `recognizer_instance.recognize_wit` for an example.

**Comment by tuming1990** [comment]
Thanks. I'll try that.

**Comment by tuming1990** [comment]
Still doesn't work. I have the segmented samples then.
Please close this issue. Thanks.

**Comment by combinatorist** [comment]
I've logged a similar issue with #130.  

The difference is I modified `examples/audio_transcribe.py` to only use the pocketSphinx recognizer. I'm using very long (hour +) pre-recorded aif files, but the process hangs (even though it works for short ones).

Just wondering if segmentation is my only option, but I'm hoping not since it's all running offline.
