### ISSUE TITLE
Google Speech API

### ISSUE THREAD

**Issue by csal3** [Uberi/speech_recognition#63]
Does this library always work? I've seen that the Google Speech API can be requested only 50 times a day, so can this be used as much as wanted even if it is using the google speech API? Also do I need to use my API key? or can I use the default one?

Thanks

**Comment by Uberi** [comment]
Hi @csal3,

* If you specify a key, the API quota is 50 requests per day.
* If you don't specify a key, there is no quota. However, this may stop working at any time in the future - it is only meant for development/testing purposes.

**Comment by csal3** [comment]
Hi,

Thanks for your reply!
What do you mean by it may stop working in the future? Do you mean the library couldn’t be used anymore? Or that if it stops working one needs to use their API key? And in the future, do you mean in the near future?

Sorry for bothering you but I am currently working on my final year project and it involves speech recognition. I was thinking of using the google speech API as a recogniser in order to avoid training data. Thus I am trying to figure if I can use such libraries.

Thanks

**Comment by Uberi** [comment]
* If Google decides to change their Chrome Speech API key, the default key will no longer work, though everything else will continue to function as normal. This would not affect you if you use an API key.
* As far as I can tell, this won't be happening any time soon. Since this library uses the same mechanism as Google Chrome, if they drop support for it, they also break speech functionality in current versions of Chrome.
* This library works with more than just the Google Speech API. The Wit.ai API, in particular, gives very good results.
* API keys are usually free. I have not paid for access to any of these in my development and testing of this library.
* None of the supported APIs require training data! However, support will be added in the next major version for CMU Sphinx, which will allow you to specify your own training data if you need to.

**Comment by csal3** [comment]
Thanks a lot for the information!
